### ISSUE TITLE
Can't load HD Packs when loading a rom from an archive

### ISSUE THREAD

**Issue by Monyet28** [libretro/Mesen#9] opened 2021-05-31 11:14 UTC
The behaviour of the RA core is different to the standalone version. If you load a rom that is within an archive, even if you name the HD pack the same as the filename.zip or the extracted rom.nes, it will not load the HD pack. It will also not load HD Packs that are zipped, only loading them when they are extracted.

**Comment by Sanaki** [comment] 2021-05-31 12:08
Can't reproduce. All my games are within 7z archives and they load HD packs fine.

**Comment by Monyet28** [comment] 2021-05-31 12:37
Well then, Any ideas? Because that's the behaviour I'm seeing. If I run rom.nes I get textures, If I run Rom.7z I get no textures. I thought maybe my path length could be a culprit which is \Launchbox\Games\Nintendo Entertainment System\rom.7z and Retroarch is stored in \Launchbox\Emulators\Retroarch\

**Comment by Sanaki** [comment] 2021-05-31 13:27
Apologies, I had been testing a build and forgot to reset it. I think you're right and we've stumbled onto a regression. I'll bisect and see what I can find.

**Comment by Monyet28** [comment] 2021-05-31 13:39
No worries, the only other variable I can give you is that I dropped the latest RA version over the top of the old one so it's not a fresh install. I found another branch of Mesen run by a MkWong98. Is this branch the one that gets put out as a core or is MkWong98's? I'm new to this so just asking.

**Comment by Sanaki** [comment] 2021-05-31 14:02
This is the correct fork for the libretro core.

The regression occurred in libretro/retroarch@334a43a7c5b072d468b8cb4d6b4d1737795d12e3. Since it's a frontend change but could be a core behavior issue, I'm not really sure which end it needs to be fixed on. Perhaps @jdgleaver would know better.

In the meantime, you can either run 1.9.3 stable or the May 19th nightly to retain archived HD pack functionality until it's sorted on one end or the other.

**Comment by Monyet28** [comment] 2021-05-31 14:57
Cool, will do. Thanks.

**Comment by jdgleaver** [comment] 2021-06-01 08:58
Please see my comment here: https://github.com/libretro/RetroArch/pull/12421#issuecomment-850832775

This is a core issue. I will have a look at fixing it once the API extension mentioned in the comment is complete (I need another day or so for this...)

**Comment by Sanaki** [comment] 2021-06-01 19:37
Oof, yeah, I didn't go so far as reading comments there. Definitely would prefer not to require `need_fullpath`. Thanks for the info.

**Comment by jdgleaver** [comment] 2021-06-04 11:20
There we go - this should solve the issue: #10

**Closed as completed** 2021-06-04 11:30 UTC

**Comment by Sanaki** [comment] 2021-06-04 20:51
Works beautifully, thank you.

**Comment by Monyet28** [comment] 2021-06-07 04:16
Cheers for that!
